# Generated by Django 5.0.6 on 2024-09-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Is_activate_image_recoganize', models.BooleanField(default=False)),
                ('Is_activate_Fingerprint_recoganize', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='otp_verification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='app.user_roles')),
            ],
        ),
        migrations.CreateModel(
            name='face_recoganizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='face_recognition_pic/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_recoganize', to='app.user_roles')),
            ],
        ),
        migrations.CreateModel(
            name='add_source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=250)),
                ('source_url', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='app.user_roles')),
            ],
        ),
    ]
