# Generated by Django 5.0.6 on 2024-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_roles',
            name='Is_activate_Fingerprint_recoganize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_roles',
            name='Is_activate_image_recoganize',
            field=models.BooleanField(default=False),
        ),
    ]
