# Generated by Django 5.0.6 on 2024-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_roles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_roles',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
