# Generated by Django 5.0.7 on 2024-08-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_roles_is_activate_fingerprint_recoganize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=250)),
                ('source_url', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='app.user_roles')),
            ],
        ),
    ]
