# Generated by Django 5.0.6 on 2024-07-19 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_roles_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_verification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='app.user_roles')),
            ],
        ),
    ]
